### ISSUE TITLE
missing email verify and forgot password 

### ISSUE THREAD

**Issue by tienthanh1993** [micro/auth-srv#2]
it's seem missing email verify and forgot password.

--' rip my english

**Comment by asim** [comment]
Where is exactly do you mean? Are you talking about missing endpoints?

**Comment by tienthanh1993** [comment]
I don't know where i can hand email verification and forgot password

**Comment by asim** [comment]
Well as you can see from the API, there's no real notion of email or password. There's accounts which have metadata which could be user, service, system or anything else and then authorisation firstly using oauth2 which has the notion of id and secret. If you're looking for something more in the user management space then maybe user-srv is more appropriate https://github.com/micro/user-srv

**Comment by tienthanh1993** [comment]
i got it thank for your time :+1:
