### ISSUE TITLE
Service tag "v=1.0.0" will not be discoverable via DNS due to invalid characters

### ISSUE THREAD

**Issue by fasilenko** [micro/auth-srv#3]
Hi!
Here is a problem...??

> $ consul -v
Consul 0.6.4.rc3
Consul Protocol: 3 (Understands back to: 1)

> $ consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul -advertise 127.0.0.1
==> WARNING: BootstrapExpect Mode is specified as 1; this is the same as Bootstrap mode.
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
         Node name: 'Alexanders-iMac'
        Datacenter: 'dc1'
            Server: true (bootstrap: true)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2016/03/16 11:16:33 [INFO] raft: Node at 127.0.0.1:8300 [Follower] entering Follower state
    2016/03/16 11:16:33 [INFO] serf: EventMemberJoin: Alexanders-iMac 127.0.0.1
    2016/03/16 11:16:33 [INFO] serf: EventMemberJoin: Alexanders-iMac.dc1 127.0.0.1
    2016/03/16 11:16:33 [INFO] consul: adding LAN server Alexanders-iMac (Addr: 127.0.0.1:8300) (DC: dc1)
    2016/03/16 11:16:33 [INFO] consul: adding WAN server Alexanders-iMac.dc1 (Addr: 127.0.0.1:8300) (DC: dc1)
    2016/03/16 11:16:33 [ERR] agent: failed to sync remote state: No cluster leader
    2016/03/16 11:16:34 [WARN] raft: Heartbeat timeout reached, starting election
    2016/03/16 11:16:34 [INFO] raft: Node at 127.0.0.1:8300 [Candidate] entering Candidate state
    2016/03/16 11:16:34 [INFO] raft: Election won. Tally: 1
    2016/03/16 11:16:34 [INFO] raft: Node at 127.0.0.1:8300 [Leader] entering Leader state
    2016/03/16 11:16:34 [INFO] consul: cluster leadership acquired
    2016/03/16 11:16:34 [INFO] raft: Disabling EnableSingleNode (bootstrap)
    2016/03/16 11:16:34 [INFO] consul: New leader elected: Alexanders-iMac
    2016/03/16 11:16:34 [INFO] consul: member 'Alexanders-iMac' joined, marking health alive
    2016/03/16 11:16:37 [INFO] agent: Synced service 'consul'
    2016/03/16 11:16:41 [WARN] Service name "go.micro.srv.auth" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2016/03/16 11:16:41 [WARN] Service tag "t={\"transport\":\"http\"}" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2016/03/16 11:16:41 [WARN] Service tag "t={\"broker\":\"http\"}" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2016/03/16 11:16:41 [WARN] Service tag "t={\"server\":\"rpc\"}" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2016/03/16 11:16:41 [WARN] Service tag "t={\"registry\":\"consul\"}" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.

> $ ./auth-srv
2016/03/16 11:16:41 Listening on [::]:53348
2016/03/16 11:16:41 Broker Listening on [::]:53349
2016/03/16 11:16:41 Registering node: go.micro.srv.auth-cbb55769-eb57-11e5-a046-10ddb1ab9e60
^C2016/03/16 11:17:28 Deregistering node: go.micro.srv.auth-cbb55769-eb57-11e5-a046-10ddb1ab9e60

Thanks for advice!

**Comment by asim** [comment]
Hey. This is not a problem, just a warning. We use consul tags to store service metadata but consul wants only alphanumeric input so that it can create DNS txt records. This does not affect functionality of micro or the auth-srv in anyway.

**Comment by asim** [comment]
Being addressed here https://github.com/micro/go-micro/pull/63
