### ISSUE TITLE
MySQL event scheduler instead of golang ticker?

### ISSUE THREAD

**Issue by fasilenko** [micro/auth-srv#4]
Hi!
Regarding feature/approach below:

    func (m *mysql) run() {
        // mysql does not expire rows so we must do so.
        t := time.NewTicker(time.Minute * 10)
        for _ = range t.C {
            // expires field is actually set in the future
            // so we take anything older than now and destroy it
            expiry := time.Now().Unix()
            m.DeleteExpired(expiry)
        }
    }

MySQL 5.1+ has event scheduler. The MySQL Event Scheduler manages the scheduling and execution of events - tasks that run according to schedule.

Stored routines require the event table in the MySQL database. This table is created during the MySQL installation procedure.

Syntax for using it would be:

    CREATE EVENT ClearUserActivationCodes
    ON SCHEDULE EVERY 1 DAY DO
    BEGIN
        DELETE FROM user_activation_code
         WHERE code_time_stamp < NOW()
    END

Details here: http://dev.mysql.com/doc/refman/5.7/en/event-scheduler.html
So, opinion?

**Comment by asim** [comment]
It's an optimisation I haven't really thought about. Is this applicable across other mysql compliant databases? How does it operate across a clustered setup?

Usually opposed to technology specific requirements and upfront setup. What requirements does this place on the user?
